config/routes.rb
Hw3::Application.routes.draw do
  get '/dice', controller: 'dice', action: 'dice', as: 'dice'
  post '/dice', controller: 'dice', action: 'dice', as: 'dice'
  post '/dice/play', controller: 'dice', action: 'play', as: 'play'
  post '/dice/alive', controller: 'dice', action: 'alive', as: 'alive'

  get '/poker', controller: 'poker', action: 'poker', as: 'poker'


  get '/rps', controller: 'rps', action: 'rps', as: 'rps'
  post '/rps/roll', controller: 'rps', action: 'roll', as: 'roll'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/dice_controller.rb
class DiceController < ApplicationController

  $win = "You win!"
  $lose = "You lose!"
  $again = "Roll again"

  def dice
  end

  def play
    @roll1 = (1..6).to_a.sample
    @roll2 = (1..6).to_a.sample
    @score = @roll1 + @roll2

    if @score == 7 ||  @score == 11
      @reply = $win
      @action = "dice"
      @button_caption = 'Start over'
    elsif
      @score == 2 ||  @score == 3 ||  @score == 12
      @reply = $lose
      @action = "dice"
      @button_caption = 'Start over'
    else
      @reply = $again
      @action = "alive"
      @button_caption = $again
    end

  end

  def alive
    @points = params[:id]
    @roll1 = (1..6).to_a.sample
    @roll2 = (1..6).to_a.sample
    @score = @roll1 + @roll2

    if @score == 7
       @reply = $lose
       @action = "dice"
       @button_caption = 'Start over'
    elsif @score == @points
       @reply = $win
       @action = "dice"
       @button_caption = 'Start over'
    else
      @reply = $again
      @action = "alive"
      @button_caption = $again
    end

  end

end

app/controllers/poker_controller.rb
class PokerController < ApplicationController

  def poker
    # create an array with 53 elements with fixnum values 0 to 52
    i = 0
    @cards = Array.new
    while i <= 52 do
      @cards << i
      i = i + 1
    end
    # create a 5-element hand array that will hold the five different cards for view
    @hand = [0,0,0,0,0]
    i = 0
    # for each of the 5 cards in array hand, pick a sample from
    # @cards, check to see if the sample element is 0 and if not,
    # add that element to the hand. an element with value 0
    # indicates that the index number already in the hand. after
    # putting an element in the hand, set it to zero in cards array.
    while i < 5 do
      random = @cards.to_a.sample
      while random == 0
        random = @cards.to_a.sample
      end
      @hand[i] = random
      @cards[random] = 0
      i = i + 1
     end
  end
end

app/controllers/rps_controller.rb
class RpsController < ApplicationController

  def rps
    @paper = 'paper.png'
    @rock = 'rock.jpg'
    @scissors = 'scissors.jpg'
  end

  def roll
    @user = params[:user_choice]
    @paper = 'paper.png'
    @rock = 'rock.jpg'
    @scissors = 'scissors.jpg'
    @option = ['paper.png', 'rock.jpg', 'scissors.jpg']
    @computer = @option.sample

    if @user.eql?(@computer)
      @result = "It's a tie."
    elsif
      @user.eql?(@paper) & @computer.eql?(@rock)
      @result = "You win!"
    elsif
      @user.eql?(@paper) & @computer.eql?(@scissors)
      @result = "You lose!"
    elsif
      @user.eql?(@rock) & @computer.eql?(@paper)
      @result = "You lose!"
    elsif
      @user.eql?(@rock) & @computer.eql?(@scissors)
      @result = "You win!"
    elsif
      @user.eql?(@scissors) & @computer.eql?(@paper)
      @result = "You win!"
    elsif
      @user.eql?(@scissors) & @computer.eql?(@rock)
      @result = "You lose!"
    end

  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/dice/alive.html.erb
<h3>You need to roll <%= @points %> before rolling a 7 to win</h3>
<p>Dice 1: <%= @roll1 %></p>
<p>Dice 2: <%= @roll2 %></p>
<p>Total: <%= @roll2+@roll1 %></p>
<p><%= @reply %></p>

<%= form_tag :action=> @action do %>
<%= hidden_field_tag :id, @points %>
<%= submit_tag(@button_caption) %>
<% end %>

app/views/dice/dice.html.erb
<h1>Dice Game </h1>
<p>
Here are the rules:</br>
Roll the dice to start the game.</br>
If your first roll is a 7 or 11, you win.</br>
If your first roll is a 2, 3 or 12, you lose.</br>
Anything else becomes your point. Roll your point again before a 7 and you win.
</p>
<%= form_tag :action=> 'play' do %>
<%= submit_tag "Play"%>
<% end %>

app/views/dice/play.html.erb
<p>Dice 1: <%= @roll1 %></p>
<p>Dice 2: <%= @roll2 %></p>
<p>Total: <%= @roll2+@roll1 %></p>
<p><%= @reply %></p>

<%= form_tag :action => @action do %>
<%= hidden_field_tag :id, @score %>
<%= submit_tag(@button_caption) %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Hw3</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/poker/poker.html.erb
<%= (image_tag @hand[0].to_s+".png") %>
<%= (image_tag @hand[1].to_s+".png") %>
<%= (image_tag @hand[2].to_s+".png") %>
<%= (image_tag @hand[3].to_s+".png") %>
<%= (image_tag @hand[4].to_s+".png") %>

<h2><%= link_to "Shuffle!", poker_path %></h2>

app/views/rps/roll.html.erb
<h2>Rock Paper Scissors</h2>
<h2>Computer played a:</h2>
<%= image_tag @computer,:height =>'200' %>

<h2>You played a:</h2>
<%= image_tag @user,:height =>'200' %>

<h3><%= @result %></h3>
<h2><%= link_to "Play again!", rps_path %></h2>

app/views/rps/rps.html.erb
<h2>Rock Paper Scissors</h2>
<%= form_tag :action=> 'roll' do %>
<%= hidden_field_tag :user_choice, @rock %>
<%= image_submit_tag((@rock),:height =>'200') %>
<% end %>

<%= form_tag :action=> 'roll' do %>
<%= hidden_field_tag :user_choice, @paper %>
<%= image_submit_tag((@paper),:height =>'200') %>
<% end %>

<%= form_tag :action=> 'roll' do %>
<%= hidden_field_tag :user_choice, @scissors %>
<%= image_submit_tag((@scissors),:height =>'200') %>
<% end %>